mqtt:
  hostname: 127.0.0.1
  port: 1883
  user: 
  password: 
deviceName: server-eu3x
deviceManufacturer: VirtualBox
deviceModel: I99
client_id: servereu
timezone: Europe/Amsterdam
update_interval: 5 #Defaults to 60
check_wifi_strength: false
check_available_updates: true
enable_rust_server: true
rust_server_ip: 
rust_rcon_port:
rcon_password: yourrconpass
#external_drives:
  #Drive1: /